sudo: required
services:
    - docker
    
before_install:
    - docker build -t cboigenreif/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run cboigenreif/react-test npm run test -- --coverage
    
after_success:
    - docker build -t cboigenreif/multi-client ./client
    - docker build -t cboigenreif/multi-nginx ./nginx
    - docker build -t cboigenreif/multi-server ./server
    - docker build -t cboigenreif/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them up to docker hub
    - docker push cboigenreif/multi-client
    - docker push cboigenreif/multi-nginx
    - docker push cboigenreif/multi-server
    - docker push cboigenreif/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-398678187888
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY